travis:
  secure:
    BINSTAR_TOKEN: flM/h1WoxNhOaHxhn+f46MhPzJID1s3mxKVnKWHhPEqyU0A5tSDEATF5W+kD/fz4ZONE4y56r++QlJA4FS+0n28Ckkgin7Cbm1fstj1BWKNlnuI5946zi3OqRHHzoeHsbS4RHEadwMGIjlqfpg07m2DtaN/+5qfBICtfxCm8UL221VNocoBncRoM8WFmiGMregynEBBP6BFTn6ZYwVj+3FpZlBa0PvSiI7rBw5RwC5ANlRMJu/PZriMyubq+T8fwTXSOA2aaKi+sl0nwPEXbNVb6KtoMRD0oM2JbaFjYUPYwRjYCQB1dEPF1wFVlYjOf5jTIZkfBxNcrHLe7DLjCHC7/5Mv9z8oZt+1QrRzi7DSFF/6t61TRVKoxYVk13mdqSjagDjpxt5rvJh4Ta1DSYz18Np8YRdOxSDKfsHTNw7xapyjnSZ502xXoOGIcPBcA6Ga0vbLPffTc68d8GkZpPouQP9+ReYlZF22Bj/7ZOLBHW6CJU8H7OMMBzDm+BNAQpCnCk6Z+7A8JwDbiF0K4GS+WGoEDj+FaVrb51hoZhd6nFO6QgsmJPcEJkgMN5/t/iD+YzMWq3bXI34GKUEPIq2DMy1owQs0Vxh1RF5eXHkQUeuZBc5iMEQedwdo/TPEAMWu0eFlD/qf5tzWuGkTTI10pYr5PwHVAHuqQI0pO7ZM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
